# Generated by Django 3.1.1 on 2020-10-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201002_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='gst',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='data',
            name='name_of_product',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='quantity_of_product',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='rate_of_product',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
